// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BrqTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("https://github.com/guitechnologic/SeleniumWebdrive"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void brqTest() {
    // Test name: BrqTest
    // Step # | name | target | value
    // 1 | open | /index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 1936x1096 | 
    driver.manage().window().setSize(new Dimension(1936, 1096));
    // 3 | click | css=#homefeatured > .ajax_block_product:nth-child(1) .replace-2x | 
    driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .replace-2x")).click();
    // 4 | click | css=.exclusive font > font | 
    driver.findElement(By.cssSelector(".exclusive font > font")).click();
    // 5 | click | css=.button-medium font > font | 
    driver.findElement(By.cssSelector(".button-medium font > font")).click();
    // 6 | click | css=.button font > font | 
    driver.findElement(By.cssSelector(".button font > font")).click();
    // 7 | click | css=#SubmitCreate font > font | 
    driver.findElement(By.cssSelector("#SubmitCreate font > font")).click();
    // 8 | type | id=email_create | fulanasilva@internet.com
    driver.findElement(By.id("email_create")).sendKeys("fulanasilva@internet.com");
    // 9 | click | css=#SubmitCreate font > font | 
    driver.findElement(By.cssSelector("#SubmitCreate font > font")).click();
    // 10 | mouseOver | id=id_gender1 | 
    {
      WebElement element = driver.findElement(By.id("id_gender1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | click | id=id_gender1 | 
    driver.findElement(By.id("id_gender1")).click();
    // 12 | mouseOut | id=id_gender1 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 13 | click | id=customer_firstname | 
    driver.findElement(By.id("customer_firstname")).click();
    // 14 | type | id=customer_firstname | Fulana
    driver.findElement(By.id("customer_firstname")).sendKeys("Fulana");
    // 15 | click | id=customer_lastname | 
    driver.findElement(By.id("customer_lastname")).click();
    // 16 | type | id=customer_lastname | Silva
    driver.findElement(By.id("customer_lastname")).sendKeys("Silva");
    // 17 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 18 | type | id=passwd | Passw0rd
    driver.findElement(By.id("passwd")).sendKeys("Passw0rd");
    // 19 | click | css=.account_creation:nth-child(1) > .form-group:nth-child(7) | 
    driver.findElement(By.cssSelector(".account_creation:nth-child(1) > .form-group:nth-child(7)")).click();
    // 20 | click | id=days | 
    driver.findElement(By.id("days")).click();
    // 21 | select | id=days | label=regexp:14\s+
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:14\\s+']")).click();
    }
    // 22 | click | id=days | 
    driver.findElement(By.id("days")).click();
    // 23 | click | id=months | 
    driver.findElement(By.id("months")).click();
    // 24 | select | id=months | label=regexp:Janeiro\s
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:Janeiro\\s']")).click();
    }
    // 25 | click | id=months | 
    driver.findElement(By.id("months")).click();
    // 26 | click | id=years | 
    driver.findElement(By.id("years")).click();
    // 27 | select | id=years | label=regexp:1990\s+
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1990\\s+']")).click();
    }
    // 28 | click | id=years | 
    driver.findElement(By.id("years")).click();
    // 29 | runScript | window.scrollTo(0,411) | 
    js.executeScript("window.scrollTo(0,411)");
    // 30 | click | id=company | 
    driver.findElement(By.id("company")).click();
    // 31 | type | id=company | internet
    driver.findElement(By.id("company")).sendKeys("internet");
    // 32 | click | id=address1 | 
    driver.findElement(By.id("address1")).click();
    // 33 | type | id=address1 | Triangle Research Park
    driver.findElement(By.id("address1")).sendKeys("Triangle Research Park");
    // 34 | type | id=address2 | house
    driver.findElement(By.id("address2")).sendKeys("house");
    // 35 | type | id=city | Carolina do norte
    driver.findElement(By.id("city")).sendKeys("Carolina do norte");
    // 36 | click | id=id_state | 
    driver.findElement(By.id("id_state")).click();
    // 37 | select | id=id_state | label=Carolina do Norte
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Carolina do Norte']")).click();
    }
    // 38 | click | id=id_state | 
    driver.findElement(By.id("id_state")).click();
    // 39 | click | id=postcode | 
    driver.findElement(By.id("postcode")).click();
    // 40 | type | id=postcode | 12345
    driver.findElement(By.id("postcode")).sendKeys("12345");
    // 41 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 42 | type | id=phone | 5551234888
    driver.findElement(By.id("phone")).sendKeys("5551234888");
    // 43 | click | id=phone_mobile | 
    driver.findElement(By.id("phone_mobile")).click();
    // 44 | type | id=phone_mobile | 5553214699
    driver.findElement(By.id("phone_mobile")).sendKeys("5553214699");
    // 45 | click | id=alias | 
    driver.findElement(By.id("alias")).click();
    // 46 | type | id=alias | My addressTriangle Park Avenus
    driver.findElement(By.id("alias")).sendKeys("My addressTriangle Park Avenus");
    // 47 | click | css=#submitAccount > span | 
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    // 48 | runScript | window.scrollTo(0,174) | 
    js.executeScript("window.scrollTo(0,174)");
    // 49 | click | css=.button-medium font > font | 
    driver.findElement(By.cssSelector(".button-medium font > font")).click();
    // 50 | click | id=cgv | 
    driver.findElement(By.id("cgv")).click();
    // 51 | click | css=.standard-checkout font > font | 
    driver.findElement(By.cssSelector(".standard-checkout font > font")).click();
    // 52 | runScript | window.scrollTo(0,300) | 
    js.executeScript("window.scrollTo(0,300)");
    // 53 | click | linkText=Pague por transferência bancária (o processamento do pedido será mais demorado) | 
    driver.findElement(By.linkText("Pague por transferência bancária (o processamento do pedido será mais demorado)")).click();
    // 54 | click | css=.button font > font | 
    driver.findElement(By.cssSelector(".button font > font")).click();
  }
}
