# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBrqTest():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='https://github.com/guitechnologic/SeleniumWebdrive', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_brqTest(self):
    # Test name: BrqTest
    # Step # | name | target | value
    # 1 | open | /index.php | 
    self.driver.get("http://automationpractice.com/index.php")
    # 2 | setWindowSize | 1936x1096 | 
    self.driver.set_window_size(1936, 1096)
    # 3 | click | css=#homefeatured > .ajax_block_product:nth-child(1) .replace-2x | 
    self.driver.find_element(By.CSS_SELECTOR, "#homefeatured > .ajax_block_product:nth-child(1) .replace-2x").click()
    # 4 | click | css=.exclusive font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".exclusive font > font").click()
    # 5 | click | css=.button-medium font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-medium font > font").click()
    # 6 | click | css=.button font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".button font > font").click()
    # 7 | click | css=#SubmitCreate font > font | 
    self.driver.find_element(By.CSS_SELECTOR, "#SubmitCreate font > font").click()
    # 8 | type | id=email_create | fulanasilva@internet.com
    self.driver.find_element(By.ID, "email_create").send_keys("fulanasilva@internet.com")
    # 9 | click | css=#SubmitCreate font > font | 
    self.driver.find_element(By.CSS_SELECTOR, "#SubmitCreate font > font").click()
    # 10 | mouseOver | id=id_gender1 | 
    element = self.driver.find_element(By.ID, "id_gender1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | click | id=id_gender1 | 
    self.driver.find_element(By.ID, "id_gender1").click()
    # 12 | mouseOut | id=id_gender1 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | id=customer_firstname | 
    self.driver.find_element(By.ID, "customer_firstname").click()
    # 14 | type | id=customer_firstname | Fulana
    self.driver.find_element(By.ID, "customer_firstname").send_keys("Fulana")
    # 15 | click | id=customer_lastname | 
    self.driver.find_element(By.ID, "customer_lastname").click()
    # 16 | type | id=customer_lastname | Silva
    self.driver.find_element(By.ID, "customer_lastname").send_keys("Silva")
    # 17 | click | id=passwd | 
    self.driver.find_element(By.ID, "passwd").click()
    # 18 | type | id=passwd | Passw0rd
    self.driver.find_element(By.ID, "passwd").send_keys("Passw0rd")
    # 19 | click | css=.account_creation:nth-child(1) > .form-group:nth-child(7) | 
    self.driver.find_element(By.CSS_SELECTOR, ".account_creation:nth-child(1) > .form-group:nth-child(7)").click()
    # 20 | click | id=days | 
    self.driver.find_element(By.ID, "days").click()
    # 21 | select | id=days | label=regexp:14\s+
    dropdown = self.driver.find_element(By.ID, "days")
    dropdown.find_element(By.XPATH, "//option[. = 'regexp:14\\s+']").click()
    # 22 | click | id=days | 
    self.driver.find_element(By.ID, "days").click()
    # 23 | click | id=months | 
    self.driver.find_element(By.ID, "months").click()
    # 24 | select | id=months | label=regexp:Janeiro\s
    dropdown = self.driver.find_element(By.ID, "months")
    dropdown.find_element(By.XPATH, "//option[. = 'regexp:Janeiro\\s']").click()
    # 25 | click | id=months | 
    self.driver.find_element(By.ID, "months").click()
    # 26 | click | id=years | 
    self.driver.find_element(By.ID, "years").click()
    # 27 | select | id=years | label=regexp:1990\s+
    dropdown = self.driver.find_element(By.ID, "years")
    dropdown.find_element(By.XPATH, "//option[. = 'regexp:1990\\s+']").click()
    # 28 | click | id=years | 
    self.driver.find_element(By.ID, "years").click()
    # 29 | runScript | window.scrollTo(0,411) | 
    self.driver.execute_script("window.scrollTo(0,411)")
    # 30 | click | id=company | 
    self.driver.find_element(By.ID, "company").click()
    # 31 | type | id=company | internet
    self.driver.find_element(By.ID, "company").send_keys("internet")
    # 32 | click | id=address1 | 
    self.driver.find_element(By.ID, "address1").click()
    # 33 | type | id=address1 | Triangle Research Park
    self.driver.find_element(By.ID, "address1").send_keys("Triangle Research Park")
    # 34 | type | id=address2 | house
    self.driver.find_element(By.ID, "address2").send_keys("house")
    # 35 | type | id=city | Carolina do norte
    self.driver.find_element(By.ID, "city").send_keys("Carolina do norte")
    # 36 | click | id=id_state | 
    self.driver.find_element(By.ID, "id_state").click()
    # 37 | select | id=id_state | label=Carolina do Norte
    dropdown = self.driver.find_element(By.ID, "id_state")
    dropdown.find_element(By.XPATH, "//option[. = 'Carolina do Norte']").click()
    # 38 | click | id=id_state | 
    self.driver.find_element(By.ID, "id_state").click()
    # 39 | click | id=postcode | 
    self.driver.find_element(By.ID, "postcode").click()
    # 40 | type | id=postcode | 12345
    self.driver.find_element(By.ID, "postcode").send_keys("12345")
    # 41 | click | id=phone | 
    self.driver.find_element(By.ID, "phone").click()
    # 42 | type | id=phone | 5551234888
    self.driver.find_element(By.ID, "phone").send_keys("5551234888")
    # 43 | click | id=phone_mobile | 
    self.driver.find_element(By.ID, "phone_mobile").click()
    # 44 | type | id=phone_mobile | 5553214699
    self.driver.find_element(By.ID, "phone_mobile").send_keys("5553214699")
    # 45 | click | id=alias | 
    self.driver.find_element(By.ID, "alias").click()
    # 46 | type | id=alias | My addressTriangle Park Avenus
    self.driver.find_element(By.ID, "alias").send_keys("My addressTriangle Park Avenus")
    # 47 | click | css=#submitAccount > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#submitAccount > span").click()
    # 48 | runScript | window.scrollTo(0,174) | 
    self.driver.execute_script("window.scrollTo(0,174)")
    # 49 | click | css=.button-medium font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-medium font > font").click()
    # 50 | click | id=cgv | 
    self.driver.find_element(By.ID, "cgv").click()
    # 51 | click | css=.standard-checkout font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".standard-checkout font > font").click()
    # 52 | runScript | window.scrollTo(0,300) | 
    self.driver.execute_script("window.scrollTo(0,300)")
    # 53 | click | linkText=Pague por transferência bancária (o processamento do pedido será mais demorado) | 
    self.driver.find_element(By.LINK_TEXT, "Pague por transferência bancária (o processamento do pedido será mais demorado)").click()
    # 54 | click | css=.button font > font | 
    self.driver.find_element(By.CSS_SELECTOR, ".button font > font").click()
  
